AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/IfUnlessModifier:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Metrics/MethodLength:
  Max: 20
  CountComments: false
  CountAsOne: ["array", "hash", "heredoc", "method_call"]

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/GuardClause:
  MinBodyLength: 2
